name: 'security-devops-action'
description: 'Run security analyzers.'
author: 'Microsoft'
branding:
  icon: 'shield'
  color: 'black'
inputs:
  command:
    description: The command to run. Defaults to run.
    default: all
    options:
      - all
      - run
      - pre-job
      - post-job
  features:
    description: A comma separated list of features to enable. Example scanning, mapping, all. Defaults to scanning.
    default: all
  config:
    description: A file path to a .gdnconfig file.
  policy:
    description: The name of the well known policy to use. Defaults to GitHub.
    default: GitHub
  categories:
    description: A comma separated list of analyzer categories to run. Values secrets, code, artifacts, IaC, containers. Example IaC,secrets. Defaults to all.
  languages:
    description: A comma separated list of languages to analyze. Example javascript, typescript. Defaults to all.
  tools:
    description: A comma separated list of analyzer tools to run. Example bandit, binskim, eslint, templateanalyzer, terrascan, trivy.
outputs:
  sarifFile:
    description: A file path to a SARIF results file.
runs:
  using: 'node16'
  main: 'lib/main.js'
  pre: 'lib/pre.js'
  post: 'lib/post.js'
